---
title: "EDA Project"
output: html_document
---



```{r setup}
library(ggplot2)
library(data.table)


videogame_ratings <- fread("ign.csv")
videogame_sales <- fread("vgrating.csv")
videogame_ranked_sales <- fread("vgsales.csv", na.strings = c("N/A",""))

str(videogame_ranked_sales)
str(videogame_sales)
str(videogame_ratings)

title_year_sales <- videogame_sales[,c(1,2,3,6,7,8,9,10)]
title_rating <- videogame_ratings[,c(3,5,6,9)]
colnames(videogame_ratings)[3] <- "Name"
colnames(videogame_ratings)[5] <- "Platform"
colnames(videogame_ratings)[9] <- "Year_of_Release"

title_year_sales$Year_of_Release <- as.integer(title_year_sales$Year_of_Release)
videogame_sales$User_Score <- as.integer(videogame_sales$User_Score)

str(title_year_sales)

#merged <- merge(title_year_sales, title_rating, by= c("Name", "Platform", "Year_of_Release"))

# determining best selling games.
global_sales_per_platform <- videogame_sales[,sum(Global_Sales),by="Platform"]
(global_sales_per_platform[order(-global_sales_per_platform$V1)])

sales_since_08 <- subset(videogame_sales, Year_of_Release >= "2008")
globalsales_since_08 <- sales_since_08[,sum(Global_Sales), by="Platform"]
(globalsales_since_08[order(-globalsales_since_08$V1)])
```

Plots below 

```{r}
#sales by year
ploty <- ggplot(data = videogame_sales, aes(x=Year_of_Release, y = Global_Sales)) + geom_bar(stat="identity")
ploty
#by console
nex <-ploty + geom_bar(stat = "identity",aes(fill = videogame_sales$Platform))
nex

#by genre
genre <- ploty + geom_bar(stat = "identity",aes(fill = videogame_sales$Genre)) + coord_flip()
genre

#by rating
mean_rating <- aggregate(videogame_sales$User_Score ~ videogame_sales$Year_of_Release,videogame_sales,mean)
#rating <- ploty + geom_line(mean_rating,aes(x= mean_rating$`videogame_sales$Year_of_Release`, y=mean_rating$`videogame_sales$User_Score`))
rating_metacritic <- ggplot(data = mean_rating, aes(x=mean_rating$`videogame_sales$Year_of_Release`, y= mean_rating$`videogame_sales$User_Score`)) + geom_bar(stat="identity")
rating_metacritic
```

```{r num_publishers_per_year}
# change to data.frame
ranked_sales <- data.frame(videogame_ranked_sales)

#remove NA's and anything with year of 2017 or greater
ranked_sales <- ranked_sales[ranked_sales$Year < 2017, ]

ranked_sales$Year <- factor(ranked_sales$Year)

publishers_per_year <- aggregate(data=ranked_sales, Publisher ~ Year, function(x) unique(x))
num_publishers_per_year <- aggregate(data=ranked_sales, Publisher ~ Year, function(x) length(unique(x)))

ggplot(na.omit(num_publishers_per_year), aes(x = as.integer(as.character(Year)), y = Publisher)) + geom_point()
```


