---
title: "EDA Project"
output: html_document
---



```{r setup}
library("ggplot2")
library('data.table')
setwd("C:/Users/Holex/Desktop/EDA_Project")

videogame_ratings <- fread("ign.csv")
videogame_sales <- fread("vgrating.csv")
str(videogame_sales)
str(videogame_ratings)



title_year_sales$Year_of_Release <- as.integer(title_year_sales$Year_of_Release)
videogame_sales$User_Score <- as.integer(videogame_sales$User_Score)

str(title_year_sales)

merged <- merge(title_year_sales, title_rating, by= c("Name", "Platform", "Year_of_Release"))


year_sales$`videogame_sales$Year_of_Release` <- as.factor(year_sales$`videogame_sales$Year_of_Release`)

year_sales$`videogame_sales$Global_Sales` <- as.factor(year_sales$`videogame_sales$Global_Sales`)




#by console
ploty <- ggplot(data = videogame_sales, aes(x=Year_of_Release, y = Global_Sales)) + geom_bar(stat="identity")
ploty

nex <-ploty + geom_bar(stat = "identity",aes(fill = videogame_sales$Platform))
nex



#by genre
genre <- ploty + geom_bar(stat = "identity",aes(fill = videogame_sales$Genre)) + coord_flip()
genre

#by rating
mean_rating <- aggregate(videogame_sales$User_Score ~ videogame_sales$Year_of_Release,videogame_sales,mean)
#rating <- ploty + geom_line(mean_rating,aes(x= mean_rating$`videogame_sales$Year_of_Release`, y=mean_rating$`videogame_sales$User_Score`))
rating_metacritic <- ggplot(data = mean_rating, aes(x=mean_rating$`videogame_sales$Year_of_Release`, y= mean_rating$`videogame_sales$User_Score`)) + geom_bar(stat="identity")
rating_metacritic




```


IGN plots

```{r}
ratings_ign <- ggplot(videogame_ratings, aes(x=Year_of_Release, y=score)) + geom_bar(stat="identity")
ratings_ign
```


