---
title: "EDA Project II"
author: "Joe Comer"
date: "November 28, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "C:/DS/Data Munging/GroupProject2/EDA_Videogame")

```



```{r}
library(data.table)
library(ggplot2)
library(dplyr)
data <- fread("ign.csv")
IGNstaff <- fread("cleanIGNo.csv")
colnames(IGNstaff) <- c("Since")
ggplot(IGNstaff) + 
    geom_histogram(aes(Since), bins=5)
```

```{r}
IGNstock <- fread("IGNstock.csv")[-1,]
Ninstock <- fread("Ninstock.csv")[-1,]
Sonystock <- fread("Sonystock.csv")[-1,]
MSstock <- fread("MSstock.csv")[-1,]

IGNstock <- IGNstock %>% mutate(index = seq(1,nrow(IGNstock),1))
Ninstock <- Ninstock %>% mutate(index = seq(1,nrow(IGNstock),1))
Sonystock <- Sonystock %>% mutate(index = seq(1,nrow(IGNstock),1))
MSstock <- MSstock %>% mutate(index = seq(1,nrow(IGNstock),1))




x_breaks <- seq(2,nrow(IGNstock), 12)
x_labels <- as.character(IGNstock$date)[x_breaks]

ggplot(data=IGNstock) +
    geom_vline(xintercept=as.Date("2008/09/15"), color = "2", linetype = "dashed", size = 2) +
    geom_line(aes(x=as.Date(date), y=as.numeric(close), group = 1, color = "6")) +
    geom_line(data = Ninstock, aes(x=as.Date(date), y=as.numeric(close), group = 1, color = "3")) +
    geom_line(data = Sonystock, aes(x=as.Date(date), y=as.numeric(close), group = 1, color = "4")) +
    geom_line(data = MSstock, aes(x=as.Date(date), y=as.numeric(close), group = 1, color = "5"))+
    scale_color_manual(labels = c("IGN", "Nintendo", "Sony", "M$"), values = c("6", "3", "4", "5")) +
    scale_y_continuous(name = "Closing Price", breaks=waiver()) + ggtitle("Game Company Stock Data Since Dec 2007") +
    scale_x_date(name="Year") + geom_text(label = "Lehman Bros Crash", x = as.Date("2010/05/15"), y = 80)
```


```{r}
articles <- fread("snippetIGNdata.csv") %>% mutate(count = 1)
article.counts <- aggregate(articles$count, by=list(Category=articles$author), FUN=sum)
colnames(article.counts) <- c("author","count")
article.counts[order(-article.counts$count),]
```
```{r}
mean(article.counts$count)
```

```{r}
ggplot(article.counts) + geom_histogram(aes(x = count), binwidth = 20)+ ggtitle("Histogram of Articles Written by Author") + scale_y_continuous(name = "Authors", breaks = waiver(), labels = c("0","30","60","90","120"))
```

```{r}
(article.mwc <- aggregate(articles$word_count, by=list(Category=articles$author), FUN=mean))
colnames(article.mwc) <- c("author","mwc")
articles.counts.mwc <- cbind(article.counts, article.mwc)
```

```{r warning=FALSE}
lm(mwc~ count, data=articles.counts.mwc)
```

```{r warning= FALSE}
ggplot(data = articles.counts.mwc, aes(x=count, y = mwc))+geom_point(aes(color=author), show.legend = FALSE) +geom_smooth(method = "lm", aes(color="2"), show.legend = FALSE) + ggtitle("Mean Wordcount by Total Articles")

```

```{r}
(article.avgscore <- aggregate(articles$score, by=list(Category=articles$author), FUN=mean))
colnames(article.avgscore) <- c("author", "avgscore")
author.score.total <- cbind(article.counts, article.avgscore)
ggplot(data = author.score.total, aes(x=count, y = avgscore))+geom_point(aes(color=author), show.legend = FALSE) +geom_smooth(method = "lm", aes(color="2"), show.legend = FALSE) + ggtitle("Average Score by Total Articles Written")

```

```{r}
ggplot(author.score.total) + geom_histogram(aes(x = avgscore), binwidth = .5)+ ggtitle("Histogram of Average Scores by Author") + scale_y_continuous(name = "Authors", breaks = waiver(), labels = c("0","10","20","30","40","50"))

```

```{r}
scores.date <- aggregate(articles$score, by=list(Category=articles$release_date), FUN=mean)
colnames(scores.date) <- c("date", "avgscore")
wc.date <- aggregate(articles$word_count, by=list(Category=articles$release_date), FUN=mean)
colnames(wc.date) <- c("date","word_count")
score.wc.date <- cbind(scores.date, word_count =wc.date$word_count)

ggplot(data = score.wc.date, aes(x=as.Date(date, format='%B %d, %Y'), y = avgscore))+geom_point(aes(color=word_count), show.legend = TRUE)  + ggtitle("Avg Score by Date") + scale_x_date(name = "Date of Publication", breaks= waiver(), labels= c("0","2012", "2014", "2016", "2018", "2020"))
```

